---
- name: Download nvm
  get_url: url=https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh dest=/tmp/nvm

- name: Install nvm
  command: bash nvm chdir=/tmp

- name: Export nvm
  lineinfile: line='export NVM_DIR=$HOME/.nvm' dest=~/.zshrc create=yes

- name: Load nvm
  lineinfile: line='[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"' dest=~/.zshrc create=yes

- name: Activate nvm
  blockinfile:
    dest: ~/.zshrc
    block: | 
      autoload -U add-zsh-hook
      load-nvmrc() {
        if [[ -f .nvmrc && -r .nvmrc ]]; then
          nvm use
        elif [[ $(nvm version) != $(nvm version default)  ]]; then
          echo "Reverting to nvm default version"
          nvm use default
        fi
      }
      add-zsh-hook chpwd load-nvmrc
      load-nvmrc

- name: Install global packages
  shell: "npm install -g {{ item }}"
  with_items:
    - vscode-json-languageservice
    - vscode-css-languageservice
    - yaml-language-server
    - dockerfile-language-server-nodejs
    - typescript-tslint-plugin
    - typescript
