---
- name: update package repository
  apt: update-cache=yes cache_valid_time=1800
  become: yes

- name: Install common packages
  apt:
    name: [
      ncdu,
      ufw,
      dos2unix,
      unzip,
      curl,
      wget,
      htop,
      moreutils,
      libevent-dev,
      apt-transport-https,
      ca-certificates,
      software-properties-common,
      apache2-utils,
      nfs-common,
      rng-tools,
      xclip
    ]
    state: latest
  become: yes
