---
- name: Install Dependencies
  become: yes
  apt:
    name: [
      openjdk-8-jdk,
      ant,
      gradle,
      maven,
      lib32ncurses5,
      lib32gomp1,
      lib32z1-dev,
      lib32gomp1,
      lib32z1-dev,
    ]

- name: Remove conflicting java packages
  become: yes
  apt:
    name: [openjdk-11*]
    state: absent

- name: Download Android SDK
  get_url:
    url=https://dl.google.com/android/repository/sdk-tools-linux-{{ version }}.zip
    dest=/tmp

- name: Unzip Android SDK
  unarchive: src=/tmp/sdk-tools-linux-{{ version }}.zip dest=/tmp

- name: Create Android SDK folder
  file: path=/opt/android-sdk-linux state=directory mode=0755
  become: yes

- name: Move Android SDK to home folder
  command: cp tools /opt/android-sdk-linux/tools -rf chdir=/tmp
  become: yes

- name: Get user name
  shell: id -u -n
  register: user_name

- name: Get user group
  shell: id -g -n
  register: user_group

- name: Set sdk folder permissions
  file:
    path=/opt/android-sdk-linux
    recurse=yes
    state=directory
    owner={{ user_name.stdout }}
    group={{ user_group.stdout }}
  become: yes

- name: Set vars
  lineinfile:
    line={{ item }}
    dest=~/.zshrc
    state=present
    create=yes
  with_items:
    - "export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64"
    - "export ANDROID_HOME=/opt/android-sdk-linux"
    - "export PATH=$PATH:$ANDROID_HOME/tools/"
    - "export PATH=$PATH:$ANDROID_HOME/platform-tools/"

- name: Install android platform-tools
  shell: "echo y | /opt/android-sdk-linux/tools/bin/sdkmanager \"platform-tools\" \"build-tools;29.0.1\" \"platforms;android-29\""
