---
- name: Import keys
  command: gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3

- name: Download rvm
  get_url: url=https://get.rvm.io dest=/tmp/rvm

- name: Install rvm
  command: bash rvm stable --ruby=1.9.3 chdir=/tmp

- name: Install global gems
  gem: name={{ item }}
  with_items:
      - tmuxinator

- name: Add tmuxinator to zshrc
  lineinfile: dest=~/.zshrc line="source ~/.bin/tmuxinator.zsh"
