---
- name: Install vim from package repository
  apt:
    name: [vim, exuberant-ctags, ack-grep]
    state: latest
  become: yes

# Download settings from own repository
- name: Download vim folder
  git:
    repo=https://github.com/radyz/vim-radyz.git
    dest=~/.vim
    force=yes

- name: Download plugin manager
  get_url:
    url=https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest=~/.vim/autoload

- name: Create symlink to vimrc
  file: src=~/.vim/.vimrc dest=~/.vimrc state=link

- name: Create symlink to hybrid theme
  file:
    src=~/.vim/colors/hybrid/colors/hybrid.vim
    dest=~/.vim/colors/hybrid.vim
    state=link

- name: Copy ackrc to home
  copy: src=ackrc dest=~/.ackrc 
